// only works for global scope workers

importScripts("Libraries/Array.js")
importScripts("Libraries/Async.js")
importScripts("Libraries/Console.js")
importScripts("Libraries/Bracketless.js")
//importScripts("Libraries/Document.js")
importScripts("Libraries/Loop.js")
importScripts("Libraries/Match.js")
importScripts("Libraries/Report.js")
importScripts("Libraries/Type.js")
importScripts("Libraries/Event.js")
importScripts("Libraries/PropertyEditor.js")
//importScripts("Libraries/Controls.js")
importScripts("Libraries/Stage.js")
importScripts("Libraries/Vector.js")
importScripts("Libraries/three.min.js")
importScripts("Libraries/threex.dynamictext2dobject.js")
importScripts("Libraries/threex.dynamictexture.js")
importScripts("Libraries/BufferGeometryUtils.js")
importScripts("Libraries/Worker.js")
importScripts("Libraries/Eat.js")
importScripts("Libraries/Javascript.js")
importScripts("Libraries/Math.js")
importScripts("Libraries/OrbitControls.js")
importScripts("Libraries/WebVR.js")
