// TODO: probably doesn't work lol

importScripts("Libraries/Array.js")
importScripts("Libraries/Async.js")
importScripts("Libraries/Bracketless.js")
importScripts("Libraries/Console.js")
//importScripts("Libraries/Controls.js")
//importScripts("Libraries/Document.js")
importScripts("Libraries/Eat.js")
importScripts("Libraries/Event.js")
importScripts("Libraries/Javascript.js")
importScripts("Libraries/Loop.js")
importScripts("Libraries/Match.js")
importScripts("Libraries/Math.js")
importScripts("Libraries/PropertyEditor.js")
importScripts("Libraries/Report.js")
importScripts("Libraries/Set.js")
//importScripts("Libraries/Stage.js")
importScripts("Libraries/String.js")
importScripts("Libraries/Type.js")
importScripts("Libraries/Vector.js")
importScripts("Libraries/Worker.js")
importScripts("Libraries/WorkerInternal.js")
